theme: minima

header_pages:
  - about.md

github_username:  hafluz
linkedin_username: henrique-augsten

minima:
  skin: dark
  social_links:
     - { platform: github,         user_url: "https://github.com/hafluz" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/henrique-augsten" }
