theme: jekyll-theme-slate
title: [Henrique Augsten's Portfolio]

# theme: minima

# header_pages:
#  - about.md
#  - portfolio.md

# github_username:  hafluz
# linkedin_username: henrique-augsten

# skin: dark


